name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: "@vsdbmv2"
      - name: install yarn
        run: npm i -g yarn
      - name: Install
        run: yarn
      - name: Tests
        run: yarn test
      - name: Running Build
        run: yarn build
      - name: Configure NPMRC
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_TOKEN }}" > ~/.npmrc
          echo "@vsdbmv2:registry=https://npm.pkg.github.com/" >> ~/.npmrc
      - name: Publish Package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Running install
        run: yarn
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{ steps.package-version.outputs.current-version}}
          release_name: v${{ steps.package-version.outputs.current-version}}
          body: |
            Changes in this Release
            - ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
